function [X y voc groups] = loadnews()
% loadnews - loads the 20 newsgroups data
%
% SYNTAX:
% [Xs y voc groups] = loadnews();
%
% The function returns (see below for details on format)
% X        the document-term matrix, in sparse matrix format
% y        the labels for each document
% voc      the vocabulary 
% groups   the names of the groups
%
% Format:
% X: Each row contains (docID, wordID, count)
% y: The labels as numbers, i.e. y(docID) = labelID (1-20)
% voc: The actual words: voc(wordID) = 'word'
% groups: The names of the newsgroups: groups(labelID) = 'name'
%
% Note that the document-term matrix is a sparse matrix of size:
% 11269-by-53975, i.e. the docID's go from 1 to 11269 and the
% wordIDs go from 1 to 53975. The labelIDs go from 1 to 20.
%    

% Read in the numerical data
X = load('train.data');
y = load('train.label');

% Read in the vocabulary
fid = fopen('vocabulary.txt');
voc = {};
voc{53975} = '';
for i=1:53975
    voc{i} = fgetl(fid);
end

% Get the groups
groups = { ...
    'alt.atheism', ...
    'comp.graphics', ...    
    'comp.os.ms-windows.misc', ...
    'comp.sys.ibm.pc.hardware', ...
    'comp.sys.mac.hardware', ...
    'comp.windows.x', ...
    'misc.forsale', ...
    'rec.autos', ...
    'rec.motorcycles', ...
    'rec.sport.baseball', ...
    'rec.sport.hockey', ...
    'sci.crypt', ...
    'sci.electronics', ...
    'sci.med', ...
    'sci.space', ...
    'soc.religion.christian', ...
    'talk.politics.guns', ...
    'talk.politics.mideast', ...
    'talk.politics.misc', ...
    'talk.religion.misc' };
